/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BarbeirosRouteImport } from './routes/barbeiros'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BarbeirosIndexRouteImport } from './routes/barbeiros.index'
import { Route as BarbeirosSlugRouteImport } from './routes/barbeiros.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeirosRoute = BarbeirosRouteImport.update({
  id: '/barbeiros',
  path: '/barbeiros',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BarbeirosIndexRoute = BarbeirosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarbeirosRoute,
} as any)
const BarbeirosSlugRoute = BarbeirosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BarbeirosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barbeiros': typeof BarbeirosRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/localizacao': typeof LocalizacaoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/login': typeof AdminLoginRoute
  '/barbeiros/$slug': typeof BarbeirosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/barbeiros/': typeof BarbeirosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/localizacao': typeof LocalizacaoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/login': typeof AdminLoginRoute
  '/barbeiros/$slug': typeof BarbeirosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/barbeiros': typeof BarbeirosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barbeiros': typeof BarbeirosRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/localizacao': typeof LocalizacaoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/login': typeof AdminLoginRoute
  '/barbeiros/$slug': typeof BarbeirosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/barbeiros/': typeof BarbeirosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/barbeiros'
    | '/entrar'
    | '/localizacao'
    | '/minha-conta'
    | '/planos'
    | '/servicos'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/login'
    | '/barbeiros/$slug'
    | '/admin/'
    | '/barbeiros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/localizacao'
    | '/minha-conta'
    | '/planos'
    | '/servicos'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/login'
    | '/barbeiros/$slug'
    | '/admin'
    | '/barbeiros'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/barbeiros'
    | '/entrar'
    | '/localizacao'
    | '/minha-conta'
    | '/planos'
    | '/servicos'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/login'
    | '/barbeiros/$slug'
    | '/admin/'
    | '/barbeiros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BarbeirosRoute: typeof BarbeirosRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PlanosRoute: typeof PlanosRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbeiros': {
      id: '/barbeiros'
      path: '/barbeiros'
      fullPath: '/barbeiros'
      preLoaderRoute: typeof BarbeirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/barbeiros/': {
      id: '/barbeiros/'
      path: '/'
      fullPath: '/barbeiros/'
      preLoaderRoute: typeof BarbeirosIndexRouteImport
      parentRoute: typeof BarbeirosRoute
    }
    '/barbeiros/$slug': {
      id: '/barbeiros/$slug'
      path: '/$slug'
      fullPath: '/barbeiros/$slug'
      preLoaderRoute: typeof BarbeirosSlugRouteImport
      parentRoute: typeof BarbeirosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BarbeirosRouteChildren {
  BarbeirosSlugRoute: typeof BarbeirosSlugRoute
  BarbeirosIndexRoute: typeof BarbeirosIndexRoute
}

const BarbeirosRouteChildren: BarbeirosRouteChildren = {
  BarbeirosSlugRoute: BarbeirosSlugRoute,
  BarbeirosIndexRoute: BarbeirosIndexRoute,
}

const BarbeirosRouteWithChildren = BarbeirosRoute._addFileChildren(
  BarbeirosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BarbeirosRoute: BarbeirosRouteWithChildren,
  EntrarRoute: EntrarRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  MinhaContaRoute: MinhaContaRoute,
  PlanosRoute: PlanosRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
