/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarbeirosRouteImport } from './routes/barbeiros'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as BarbeirosIndexRouteImport } from './routes/barbeiros.index'
import { Route as BarbeirosSlugRouteImport } from './routes/barbeiros.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeirosRoute = BarbeirosRouteImport.update({
  id: '/barbeiros',
  path: '/barbeiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeirosIndexRoute = BarbeirosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarbeirosRoute,
} as any)
const BarbeirosSlugRoute = BarbeirosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BarbeirosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barbeiros': typeof BarbeirosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/barbeiros/$slug': typeof BarbeirosSlugRoute
  '/barbeiros/': typeof BarbeirosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servicos': typeof ServicosRoute
  '/barbeiros/$slug': typeof BarbeirosSlugRoute
  '/barbeiros': typeof BarbeirosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barbeiros': typeof BarbeirosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/barbeiros/$slug': typeof BarbeirosSlugRoute
  '/barbeiros/': typeof BarbeirosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/barbeiros' | '/servicos' | '/barbeiros/$slug' | '/barbeiros/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servicos' | '/barbeiros/$slug' | '/barbeiros'
  id:
    | '__root__'
    | '/'
    | '/barbeiros'
    | '/servicos'
    | '/barbeiros/$slug'
    | '/barbeiros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarbeirosRoute: typeof BarbeirosRouteWithChildren
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbeiros': {
      id: '/barbeiros'
      path: '/barbeiros'
      fullPath: '/barbeiros'
      preLoaderRoute: typeof BarbeirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbeiros/': {
      id: '/barbeiros/'
      path: '/'
      fullPath: '/barbeiros/'
      preLoaderRoute: typeof BarbeirosIndexRouteImport
      parentRoute: typeof BarbeirosRoute
    }
    '/barbeiros/$slug': {
      id: '/barbeiros/$slug'
      path: '/$slug'
      fullPath: '/barbeiros/$slug'
      preLoaderRoute: typeof BarbeirosSlugRouteImport
      parentRoute: typeof BarbeirosRoute
    }
  }
}

interface BarbeirosRouteChildren {
  BarbeirosSlugRoute: typeof BarbeirosSlugRoute
  BarbeirosIndexRoute: typeof BarbeirosIndexRoute
}

const BarbeirosRouteChildren: BarbeirosRouteChildren = {
  BarbeirosSlugRoute: BarbeirosSlugRoute,
  BarbeirosIndexRoute: BarbeirosIndexRoute,
}

const BarbeirosRouteWithChildren = BarbeirosRoute._addFileChildren(
  BarbeirosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarbeirosRoute: BarbeirosRouteWithChildren,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
